sudo: required
services:
    - docker

before_install:
    - docker build -t venkateshprasad/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true venkateshprasad/react-test npm test -- --coverage

after_success:
    - docker build -t venkateshprasad/multi-client ./client
    - docker build -t venkateshprasad/multi-nginx ./nginx
    - docker build -t venkateshprasad/multi-server ./server
    - docker build -t venkateshprasad/multi-worker ./worker
    #Log in to docker CLI
    - echo "aaipappa90@GPword" | docker login -u "$DOCKER_ID" --password-stdin
    #Take the images and push them to dockerhub
    - docker push venkateshprasad/multi-client
    - docker push venkateshprasad/multi-nginx
    - docker push venkateshprasad/multi-server
    - docker push venkateshprasad/multi-worker
