version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '3050:80'
    api:
        depends_on: 
            - postgres
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432    
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
    worker:
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379        
        build: 
            context: ./worker
            dockerfile: Dockerfile.dev            